// Generated by CoffeeScript 1.7.1
(function() {
  chrome.tabs.query({
    active: true,
    lastFocusedWindow: true
  }, function(tabs) {
    var tab;
    tab = tabs[0];
    if (typeof tab !== "undefined") {
      $(".title").val(tab.title);
      $(".url").val(tab.url);
    }
    $(".cancel").click(function() {
      return window.close();
    });
    return $(".add").click(function() {
      var tags, title, url;
      title = $(".title").val();
      url = $(".url").val();
      tags = $(".tags").val();
      if (!url) {
        alert("you must have a url");
        return false;
      }
      if (!title) {
        alert("you must have a title");
        return false;
      }
      if (!tags) {
        alert("you must have tags");
        return false;
      }
      return addBookmark(JSON.parse(localStorage.data), {
        title: title,
        url: url,
        tags: tags
      }, true, function(err) {
        if (err) {
          return alert(err);
        } else {
          return chrome.pageAction.setIcon({
            tabId: tab.id,
            path: "icons/heart_b_24.png"
          }, function() {
            return window.close();
          });
        }
      });
    });
  });

}).call(this);

//# sourceMappingURL=popup.map
